# -- 코드를 입력하세요
# SELECT PLACES.ID, PLACES.NAME, COUNT(PLACES.ID) AS "임대 가능일"
# FROM PLACES
# INNER JOIN SCHEDULES
# ON PLACES.ID = SCHEDULES.PLACE_ID
# WHERE SCHEDULES.SCHEDULED_AT IS NOT NULL
# GROUP BY SCHEDULES.PLACE_ID
